# Generated by Django 5.0.6 on 2024-07-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='商品名')),
                ('amount', models.IntegerField(verbose_name='在庫数')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='商品名')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.IntegerField(verbose_name='価格')),
            ],
        ),
    ]
